.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RESTIFY\-RESPONSE" "7" "September 2011" "" ""
.
.SH "NAME"
\fBrestify\-response\fR \- The Response Object
.
.SH "SYNOPSIS"
.
.nf

response: {
  accept: \'application/json\',
  requestId: uuid(),
  send: function(options),
  sendError: function(restifyError),
  sentError: boolean,
  startTime: new Date()\.getTime(),
}
.
.fi
.
.SH "DESCRIPTION"
The restify response object is simply a set of extensions over the standard node\.js http response object\.
.
.P
The additional parameters placed on the request object are:
.
.TP
accept
Contains a parsed out version of the \'Accept\' header sent from the client, for one of restify\'s supported formats\. For example, if the client sends */*, like curl does, accept will be application/json\.
.
.TP
requestId
Is a random uuid set to the same value as on the request object\. It is returned to the client in the \fBx\-request\-id\fR header\. You should log this\.
.
.TP
send
\fBsend\fR is the main extension to the request object, as it wraps up the node\.js writeHead/write/end paradigm\. This method exists for you to really pass in a JS object, and have that object formatted in a type that restify can serialize, and matches what the client sent in the Accept header\. See \fISEND\fR for more information\.
.
.TP
sendError
A wrapper method over \fBsend\fR that takes a restify \fBerror\fR object, as returned from \fBrestify\.newError\fR\. See \fIERRORS\fR for more information\.
.
.TP
sentError
A boolean that is set automatically by \fBsendError\fR\. You can use this in post filters for logging, etc\.
.
.TP
startTime
The time this request arrived at the server\. Note that this timestamp is when node\.js gives us the request object; so before the body is read, but after the headers are\. It\'s in milliseconds since epoch\.
.
.SH "SEND"
As noted in the getting started manual, there are two forms of the \fBsend\fR function:
.
.IP "" 4
.
.nf

send(code, object, headers);
send(options);
.
.fi
.
.IP "" 0
.
.P
Where \fBsend(code, object, headers)\fR takes a Number (HTTP status code), Object (the JS object you want to send back), and optional Object of headers\. If you provide the headers object, it is merged in with the standard headers that restify fills in for you\. Those headers are:
.
.IP "\(bu" 4
Access\-Control\-Allow\-Origin: *
.
.IP "\(bu" 4
Access\-Control\-Allow\-Methods: [list of methods set on this uri]
.
.IP "\(bu" 4
Connection: Close
.
.IP "\(bu" 4
Content\-Length
.
.IP "\(bu" 4
Content\-Type
.
.IP "\(bu" 4
Content\-MD5
.
.IP "\(bu" 4
Date (RFC 1123 format, in UTC)
.
.IP "\(bu" 4
Server
.
.IP "\(bu" 4
X\-Request\-Id
.
.IP "\(bu" 4
X\-Response\-Time (milliseconds)
.
.IP "\(bu" 4
X\-Api\-Version (if set on createServer)
.
.IP "" 0
.
.P
The \fBsend(options)\fR form has the following parameters:
.
.IP "" 4
.
.nf

send({
  code: 200,
  headers: {},
  body: {},
  noClose: boolean,
  noEnd: boolean,
  noContentMD5: boolean
});
.
.fi
.
.IP "" 0
.
.P
This method is used if you want to send back content that restify really doesn\'t know what to do with, but you still want to pick up the standard headers (like request\-id, date, etc\.)\. You do this with the \fBnoClose\fR and \fBnoEnd\fR options\. In general, if you want to send back something else to clients, you probably want to invoke \fBsend\fR as such:
.
.IP "" 4
.
.nf

response\.send({
  code: 200,
  headers: {
    \'Content\-Type\': \'text/html\',
    \'Trailer\': \'Content\-MD5\',
  },
  noEnd: true
};

var hash = crypto\.createHash(\'md5\');
\.\.\.
response\.write(data);
hash\.update(data);
\.\.\.
res\.addTrailers({\'Content\-MD5\': hash\.digest(\'base64\')});
res\.end();
.
.fi
.
.IP "" 0
.
.SH "ERRORS"
The response object also has a \fBsendError\fR object that is helpful for marshalling back \'standard\' error messages to clients\. Standard here means consistent, not some actual RFC (there is none)\. This is particularly useful, as it is often the case that an HTTP status code alone is not sufficient for a client to switch on\. Additionally, restify uses this error method internally, so you are advised to use it so that your errors fit the same spec\. The error object restify works with is a standard JS \fBError\fR object that has the following fields:
.
.IP "" 4
.
.nf

{
  name: \'HttpError\',                 // Standard Error field
  httpCode: <HttpStatusCode>,        // Number
  restCode: \'StringInThisFormat\',    // String client can switch on
  message: \'Human readable string\',  // Whatever you want
  error: Error,                      // An Error \'cause\'
  details: {                         // Whatever you want
    \.\.\.
  }
}
.
.fi
.
.IP "" 0
.
.P
There are built\-ins for all codes defined in \fBrestify\.RestCodes\fR, and you can chuck them into \fBnext()\fR like so:
.
.IP "" 4
.
.nf

server\.get(\'/foo\', function(req, res, next) {
  return next(new restify\.BadRequestError(\'you did something wrong\'));
});
.
.fi
.
.IP "" 0
.
.P
In previous versions of restify, you used like \fBrestify\.newError\fR:
.
.IP "" 4
.
.nf

response\.sendError(restify\.newError({
  httpCode: 409,
  restCode: \'YouAreABadClient\',
  message: \'Stop sending me bad stuff\',
  details: {
    foo: \'bar\',
  }
}));
.
.fi
.
.IP "" 0
.
.P
HttpCodes are defined on \fBrestify\.HttpCodes\fR, and there are some standard REST code strings on \fBrestify\.RestCodes\fR\. RestCodes has the following:
.
.IP "\(bu" 4
BadRequest: \'BadRequest\'
.
.IP "\(bu" 4
InternalError: \'InternalError\'
.
.IP "\(bu" 4
InvalidArgument: \'InvalidArgument\'
.
.IP "\(bu" 4
InvalidCredentials: \'InvalidCredentials\'
.
.IP "\(bu" 4
InvalidHeader: \'InvalidHeader\'
.
.IP "\(bu" 4
InvalidVersion: \'InvalidVersion\'
.
.IP "\(bu" 4
MissingParameter: \'MissingParameter\'
.
.IP "\(bu" 4
NotAuthorized: \'NotAuthorized\'
.
.IP "\(bu" 4
RequestThrottled: \'RequestThrottled\'
.
.IP "\(bu" 4
RequestTooLarge: \'RequestTooLarge\'
.
.IP "\(bu" 4
ResourceMoved: \'ResourceMoved\'
.
.IP "\(bu" 4
ResourceNotFound: \'ResourceNotFound\'
.
.IP "\(bu" 4
RetriesExceeded: \'RetriesExceeded\'
.
.IP "\(bu" 4
UnknownError: \'UnknownError\'
.
.IP "" 0
.
.P
If you don\'t set \fBrestCode\fR, restify sets it to \fIUnknownError\fR\. If you don\'t set \fBmessage\fR, restify sets it to \fIUnknown error occured\.\fR\. Details and error are not required, and are not set if not present\.
.
.SH "SECURITY CONSIDERATIONS"
Don\'t send back JS \fBError\fR objects on the \fBsendError\fR in production usage\. That will have your stack traces, etc\. Bad news\.
.
.SH "COPYRIGHT/LICENSE"
Copyright 2011 Mark Cavage \fImcavage@gmail\.com\fR
.
.P
This software is licensed under the MIT License\.
.
.SH "SEE ALSO"
restify(3), restify\-request(7)
