.\" generated with Ronn/v0.7.3
.\" http://github.com/rtomayko/ronn/tree/0.7.3
.
.TH "RESTIFY\-ROUTES" "7" "August 2011" "" ""
.
.SH "NAME"
\fBrestify\-routes\fR \- Routing in Restify
.
.SH "SYNOPSIS"
.
.nf

function authenticate(req, res, next) {
  // Check the Authorization header
  return next();
}

function authorize(req, res, next) {
  // Check ownership of resource
  return next();
}

function audit(req, res, next) {
  // Log this request/response
  return next();
}

var pre = [
  authenticate,
  authorize
];

var post = [
  log\.w3c,
  audit
];

server\.get(\'1\.2\.3\', \'/your/:param/:id\', pre, function(req, res, next) {
  res\.send(200, {
    id: req\.uriParams\.id,
    message: \'You sent \' + req\.uriParams\.param,
    sent: req\.params
  });
  return next();
}, post);

server\.get(/^\e/img\e/*/, function(req, res, next) {
  fs\.readFile(\'\./media\' + req\.url, \'utf8\', function(err, file) {
    if (err) {
      res\.writeHead(500);
      response\.end();
      return next();
    }

    res\.writeHead(200);
    res\.write(file);
    res\.end();
    return next();
  });
};
.
.fi
.
.SH "DESCRIPTION"
Restify routing is similar to, but different than, express and sinatra\. You define, at minimum, a URL which is optionally parameretized (with \':\' prefixes), and any number of handler functions\. You can substitute a \fBRegExp\fR for the string URL if you like\. Additionally, you can version a route; see restify\-versions(7) for details on versioning\. Last but not least, a key feature of restify is that you can set up \fBpre\fR and \fBpost\fR handlers that run before and after your \fBmain\fR handlers (can be any number of functions or arrays of functions)\.
.
.P
When using the string syntax for a URL, you can optionally paramterize any section of it with \fB:parameters\fR, and anything in the syntax \fB:param\fR in your url gets set on the \fBrequest\.uriParams\fR object with that name\.
.
.P
Each function in your chain is responsible for calling \fBnext()\fR otherwise the processing chain will stop\.
.
.P
A special pattern in restify is the notion of passing in an array for the first and last handlers\. Doing so makes restify automatically treat them as \fBpre\fR and \fBpost\fR, respectively\. This has the following semnatics:
.
.IP "\(bu" 4
\fBpre[0]\fR is guaranteed to be called\. If you do not call \fBresponse\.send\fR or \fBresponse\.sendError\fR in your \fBpre\fR chain, and your pre functions all call \fBnext()\fR, your \fBmain\fR chain will get invoked\. If your pre chain calls \fBresponse\.send\fR or \fBresponse\.sendError\fR, your \fBmain\fR chain will be skipped, and \fBpost[0]\fR will be invoked next (assuming you are still calling \fBnext()\fR)\.
.
.IP "\(bu" 4
Once in your \fBmain\fR chain, if you call \fBresponse\.sendError\fR, restify will stop processing your \fBmain\fR handlers, and skip to \fBpost\fR\. Calling \fBresponse\.send\fR does not have this effect, as you are expected to call \fBresponse\.send\fR as part of a "normal" request\.
.
.IP "\(bu" 4
Once your \fBpost\fR chain is invoked, restify stops playing with ordering\.
.
.IP "" 0
.
.P
Note that for this to work as described, you \fIstill have to call next()\fR in your functions\. If you don\'t, your chain gets dropped\. It\'s that simple\.
.
.P
Also note that if you\'re not using an array of functions for the first and last handlers, restify does not perform the logic above\. It instead falls back to what express does, and it\'s up to you to manage your call chain\.
.
.P
As to URL parameters, note that they can be either parameterized string URLs, (e\.g\., \fB/:user/stuff/:id\fR) or a \fBRegExp\fR\. In either case, the parameters are available to your handler functions as \fBrequest\.uriParams\fR\. In the non\-regex case, they\'re as you named them (minus the \':\', of course)\. In the \fBRegExp\fR case, they\'re available in the array \fBRegExp\.exec()\fR returns\.
.
.SH "HTTP VERBS"
Currently restify supports the following verbs as route definitions:
.
.IP "\(bu" 4
HEAD: server\.head(\.\.\.)
.
.IP "\(bu" 4
GET: server\.get(\.\.\.)
.
.IP "\(bu" 4
POST: server\.post(\.\.\.)
.
.IP "\(bu" 4
PUT: server\.put(\.\.\.)
.
.IP "\(bu" 4
DELETE: server\.del(\.\.\.)
.
.IP "" 0
.
.SH "RESTIFY ERROR RESPONSES"
When a request comes in, and there is no matching resource at all, restify will return a 404 error message to the client\. If the resource does exist, but there is not a matching route for the given verb, restify will return a 405\. Lastly, if there is both a resource and a URL, but not a matching version, restify will return a 449 with an \fBx\-api\-versions\fR\. 449 is a Microsoft HTTP extension status code that means \'retry\-with\'; I chose to snag that and use it here to mean \'retry with a different version\'\. Restify does not pass back any MS headers\.
.
.SH "ACCESS\-CONTROL\-ALLOW\-METHODS"
restify automatically inserts an access\-control\-allow\-methods header on \fBresponse\.send\fR, and fills it in with all verbs that match the current resource\.
.
.P
For example, the following code:
.
.IP "" 4
.
.nf

server\.get(\'/foo\', function(req, res, next) { \.\.\. });
server\.put(\'/foo\', function(req, res, next) { \.\.\. });
server\.del(\'/foo\', function(req, res, next) { \.\.\. });
.
.fi
.
.IP "" 0
.
.P
Would result in restify sending back an access\-control\-allow\-methods header that was the array \fB[GET, PUT, DELETE]\fR when a request was issued against \fB/foo\fR\.
.
.SH "HTTP OPTIONS"
Restify automatically supports the HTTP OPTIONS verb based on your routes\. You can call OPTIONS against either a specific resource or \fB*\fR\. Either way, restify handles it, and currently does not expose the ability to override it\.
.
.SH "COPYRIGHT/LICENSE"
Copyright 2011 Mark Cavage \fImcavage@gmail\.com\fR
.
.P
This software is licensed under the MIT License\.
.
.SH "SEE ALSO"
restify(3), restify\-versions(7)
