on:
  push:
    branches:
      - master
      - 9.x
permissions:
  contents: write
  issues: write
  pull-requests: write
name: release-please
jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          release-type: node
          target-branch: ${{ github.ref_name }}
